# Site settings
author: Emrich-Michael Perrier
title: My Software Engineering Journey w/ FlatIron School
header-img: img/home-bg.png
email: emrichmp@gmail.com
copyright_name: Emrich-Michael Perrier
description: > # this means to ignore newlines until "baseurl:"
  <3
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  emrichmp

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
